### ISSUE TITLE
[OpenAPI Spec][Eth2] DepositSigning object contains unused element and scoping typo

### ISSUE THREAD

**Issue by Magicking** [ConsenSys/web3signer#287]
The openapi spec for eth2 signing at `core/src/main/resources/openapi/web3signer-eth2.yaml` seems to have the discriminator element `type` at the `deposit` element level instead of being at the `DepositSigning` level.
The signingRoot while having acceptance for deposit doesn't seems to be used as the input is directly used as a `DepositMessage` to compute the signingRoot based on `pubkey/withdr[...]/amount`.
Current:
```
    DepositSigning:
      type: object
      properties:
        deposit:
          type: object
          properties:
            type:
              type: "string"
            signingRoot:
              type: "string"
            pubkey:
              type: "string"
            withdrawal_credentials:
              type: "string"
            amount:
              type: "string"
      required:
        - deposit
```
Proposed changes:
```
    DepositSigning:
      type: object
      properties:
        type:
          type: "string"
        deposit:
          type: object
          properties:
            pubkey:
              type: "string"
            withdrawal_credentials:
              type: "string"
            amount:
              type: "string"
      required:
        - type
        - deposit
```
