### ISSUE TITLE
Unable to read yaml strings without double quotes

### ISSUE THREAD

**Issue by prestonvanloon** [ConsenSys/web3signer#485]
This may be more of a go-yaml bug/issue than web3signer, but filing here anyway for visibility.

Annoyingly, go-yaml.v2 will only write strings with double quotes when the absence of double quotes changes the behavior of the string. I.e. if the value was `10` would parse as an integer rather than a string like `"10"`. 

```yaml
type: file-raw
keyType: SECP256K1
privateKey: 0x25b1166a43c109cb330af8945d364722757c65ed2bfed5444b5a2f057f82d391
```

web3signer does not parse the above file. at least the privateKey
```
2022-01-14 20:29:03.066+00:00 | ForkJoinPool-1-worker-3 | ERROR | SignerLoader | Error parsing signing metadata file /tmp/web3signerkeystore/key-0xa43512dbaaa3510a2a287a79228ddd9095daae775a7f5b6de337168ad1c2403308935f98a3f0de18059089ddd04617d3.yaml: MismatchedInputException: Missing required creator property 'privateKey' (index 0)
```

See: https://github.com/go-yaml/yaml/issues/556
