### ISSUE TITLE
[23.6.0] vault-agent - http2: invalid Upgrade request header: ["h2c"]

### ISSUE THREAD

**Issue by gg718** [ConsenSys/web3signer#811]
Just upgraded to Web3Signer v23.6.0 and started seeing this error in my [vault-agent](https://developer.hashicorp.com/vault/docs/agent) proxy logs:

> `2023-06-19T10:30:06.722Z [ERROR] agent.apiproxy.client: request failed: error="Get \"https://vault.example.com/v1/secret/data/goerli/12345\": http2: invalid Upgrade request header: [\"h2c\"]" method=GET url=https://vault.example.com/v1/secret/data/goerli/12345`

This error was not happening in v23.3.1 so seems to be a new bug.

Config example:

```yaml
keyName: key
keyPath: /v1/secret/data/goerli/12345
keyType: BLS
serverHost: localhost
serverPort: 8200
timeout: 30000
tlsEnabled: false
token: unused_handled_by_vault_agent
type: hashicorp
```

Where `localhost:8200` is the local port my Vault Agent is listening on.
