### ISSUE TITLE
Is it possible to unload HashiCorp Vault keys from Web3Signer?

### ISSUE THREAD

**Issue by gg718** [Consensys/web3signer#894]
### Issue

Using v23.8.1, it seems that once a key has been loaded via the HashiCorp Vault method, it is not possible to unload a key without a hard-restart.

### Repro

* Enable the [Keymanager API](https://consensys.github.io/web3signer/web3signer-eth2.html#tag/Keymanager).

* Write a key file to disk with a config similar to the following:

```yaml
keyName: key
keyPath: /v1/secret/data/goerli/12345
keyType: BLS
serverHost: localhost
serverPort: 8200
timeout: 30000
tlsEnabled: false
token: unused_handled_by_vault_proxy
type: hashicorp
```

* Use the `DELETE /eth/v1/keystores` endpoint to attempt to unload the key. Receive an error similar to:

```json
{
  "data": [
    {
      "status": "error",
      "message": "Unable to delete readonly key: 0xaffc434cf8138634a4cd0ef6cb815febd3db25760b1b6c522f9b4aa78e599b60336d7dd2e953192e45d4ac91f66f0723"
    }
  ],
  "slashing_protection": "<snip>"
}
```

* Delete the key file from disk and hit the `POST /reload` endpoint. The key is still not unloaded.

---

So, is it possible to unload a key from Web3Signer without deleting the file from disk and doing a hard-restart of the entire process, resulting in downtime?
