### ISSUE TITLE
Implement `unixSocket` as an option for communicating with Vault

### ISSUE THREAD

**Issue by gg718** [Consensys/web3signer#972]
I'm currently running a [Vault Proxy](https://developer.hashicorp.com/vault/docs/agent-and-proxy/proxy) sidecar alongside Web3Signer to handle auth and forward requests to Vault.

Each key file looks something like this:

```yaml
keyName: key
keyPath: /v1/secret/data/holesky/12345
keyType: BLS
serverHost: localhost
serverPort: 8200
timeout: 30000
tlsEnabled: false
token: unused_handled_by_vault_proxy
type: hashicorp
```

In order to improve security (and, to an minimal extent, performance), it would be great to be able to configure Vault Proxy to use unix sockets:

```hcl
listener "unix" {
  address = "/var/run/vault.sock"
}
```

and then specify:

```yaml
unixSocket: /var/run/vault.sock
```

Rather than:

```yaml
serverHost: localhost
serverPort: 8200
```

As it stands, any user able to access that port (e.g. via `kubectl port-forward`) can easily make authenticated requests to Vault via port 8200. Being able to send requests via a unix socket would improve the situation.
